# Generated by Django 2.0 on 2020-06-29 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cmdcase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmdcasename', models.CharField(max_length=200, verbose_name='用例名称')),
                ('cmdtestresult', models.BooleanField(verbose_name='测试结果')),
                ('cmdtester', models.CharField(max_length=16, verbose_name='测试负责人')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('Product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
            options={
                'verbose_name': 'cmd测试用例',
                'verbose_name_plural': 'cmd测试用例',
            },
        ),
        migrations.CreateModel(
            name='Cmdcasestep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmdteststep', models.CharField(max_length=200, verbose_name='测试步聚')),
                ('cmdtestobjname', models.CharField(max_length=200, verbose_name='cmd命令')),
                ('assertdeclare', models.CharField(max_length=200, verbose_name='断言种类')),
                ('assertInfo1', models.CharField(max_length=200, verbose_name='断言命令1')),
                ('assertInfo2', models.CharField(blank=True, max_length=200, null=True, verbose_name='断言命令2')),
                ('assertInfo3', models.CharField(blank=True, max_length=200, null=True, verbose_name='断言命令3')),
                ('assertInfo4', models.CharField(blank=True, max_length=200, null=True, verbose_name='断言命令4')),
                ('cmdtestdata', models.CharField(blank=True, max_length=200, null=True, verbose_name='测试数据')),
                ('cmdtestresult', models.BooleanField(verbose_name='测试结果')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('Cmdcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdtest.Cmdcase')),
            ],
        ),
    ]
