# Generated by Django 2.0.2 on 2020-07-07 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webtest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webcasestep',
            name='webcasename',
        ),
    ]
