# Generated by Django 2.0.2 on 2020-07-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apis',
            name='apiresponse',
            field=models.CharField(max_length=5000, null=True, verbose_name='响应数据'),
        ),
        migrations.AddField(
            model_name='apis',
            name='apitester',
            field=models.CharField(max_length=16, null=True, verbose_name='测试负责人'),
        ),
        migrations.AlterField(
            model_name='apis',
            name='apimethod',
            field=models.CharField(choices=[('get', 'get'), ('post', 'post'), ('put', 'put'), ('delete', 'delete'), ('patch', 'patch')], default='get', max_length=200, null=True, verbose_name='请求方法'),
        ),
    ]
